### ISSUE TITLE
DistributedMap race condition

### ISSUE THREAD

**Issue by laino** [kregfile/kregfile#54]
Since messages to the sync channel arrive over a different TCP connection than the response to HGETALL, the map has race conditions.

Example:

```
1st Connection            Client         2nd Connection
 m={a:1}                     |--- GET m ----| ...
 delete m.a                  |              | ...
 notify m.a -- delete m.a -->|              | ...
                             |<-- m={a:1} --|
 m={}                     m={a:1}
```

For your map you just have to queue updates and replay them once it's fully loaded.
The solution may differ depending on your data structure and how your update actions look like.

**Comment by RealDolos** [comment]
Actual problem:

* Upon construction, redis is queried, which can take some time.
*  In the meantime before the initial query result arrives, pubsub notification may already arrive (redis is using a different connection for that).
* Any early notifications will be overwritten by the now stale result of the initial construction query that finally arrived and thus lost, causing the map to be out of sync.
