### ISSUE TITLE
CSP update broke gravatar 

### ISSUE THREAD

**Issue by voroneril** [kregfile/kregfile#65]
Referring to this commit https://github.com/kregfile/kregfile/commit/f1c2f1cffd96b6ed5bd96f39495965db95aac381

![image](https://user-images.githubusercontent.com/15366201/126845734-ee573edc-8a41-4db4-87ae-90e753f473b6.png)

**Comment by RealDolos** [comment]
Yeah, I know, I fatfingered the CSP and fixed that a couple of hours ago, but didn't push it yet

**Comment by RealDolos** [comment]
a8dc0c92803131a21fbd7f333901f66fcab1a185
