### ISSUE TITLE
Chat Improvement: Click on person's name to @ them in the chat

### ISSUE THREAD

**Issue by apoapostolov** [kregfile/kregfile#77]
The purpose of this is to simplify communication and thanking uploaders. Often typing @ manually can lead to mistakes, etc. 

Clicking on the avatar icon (small circle) before the name can remain link to that user's profile.

**Comment by RealDolos** [comment]
you don't type @ at all, just type the name
and you can autocomplete names with tab even, at least if they recently talked and your browser remembers them.

**Comment by apoapostolov** [comment]
Thanks, this issue doesn't need to remain open anymore.
